// dep-graph.mjs — renders the src module graph as a Mermaid flowchart.
// Writes temp/dependency-graph.md. Values come from dependency-cruiser's
// JSON report (runtime edges, post-compilation), so this graph matches what
// `npm run dep:check` gates on. Pairs with the function-level `npm run rent`.

import { execFileSync } from 'node:child_process';
import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

// Node 20.12+/24 refuses to spawn .cmd shims (EINVAL) and the package exports
// map locks ./bin, so run the ESM binary straight from node_modules.
const here = path.dirname(fileURLToPath(import.meta.url));
const bin = path.join(here, '..', 'node_modules', 'dependency-cruiser', 'bin', 'dependency-cruise.mjs');
const out = execFileSync(
  process.execPath,
  [bin, 'src', '--include-only', '^src', '--output-type', 'json'],
  { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 }
);
const report = JSON.parse(out);

const id = (s) => s.replace(/[^a-zA-Z0-9]/g, '_');
const edges = new Set();
const lines = ['```mermaid', 'flowchart LR'];
for (const m of report.modules) {
  for (const d of m.dependencies || []) {
    if (!d.resolved || !/\.ts$/.test(d.resolved)) continue;
    const key = `${m.source}>${d.resolved}`;
    if (edges.has(key)) continue;
    edges.add(key);
    const cycle = d.cycle ? `|CYCLE:${String(d.cycle.flat().join(' > '))}|` : '';
    lines.push(`  ${id(m.source)}["${m.source}"] -->${cycle} ${id(d.resolved)}["${d.resolved}"]`);
  }
}
lines.push('```');

mkdirSync('temp', { recursive: true });
writeFileSync(
  'temp/dependency-graph.md',
  `# src module graph (runtime edges)\n\n${report.modules.length} nodes, ${edges.size} edges. Generated by \`npm run dep:graph\`.\n\n` +
    lines.join('\n') +
    '\n'
);
console.log(`temp/dependency-graph.md: ${report.modules.length} nodes, ${edges.size} edges`);
